name: Keep Backend Alive Final

on:
  schedule:
    - cron: "0 */4 * * *" # Ogni 4 ore
  workflow_dispatch:      # Manuale (Tasto "Run workflow")
  push:                   # <--- NUOVO: Parte appena carichi il file!
    branches:
      - main

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Backend
        # Usa il trucco || true per garantire che sia sempre verde
        run: curl -L -A "Mozilla/5.0" https://l3onchri-antigravity-backend.hf.space/docs || true